name = "status"
type = "javascript"
account_id = "287572e2291030d8c5e360fcc593a16b"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-05-04"
kv_namespaces = [
    { binding = "SERVICES", id = "5f40026cc97041549aae3971b9334a8c", preview_id = "ac95881f85ef4751943d6a01ff92ce33" }
]

[triggers]
crons = ["*/1 * * * *"]

[site]
bucket = ".output/public"
entry-point = ".output"

[build]
command = "true"
upload.format = "service-worker"
