name = "status"
main = ".output/server/index.mjs"
account_id = "287572e2291030d8c5e360fcc593a16b"
workers_dev = true
compatibility_date = "2022-05-04"

kv_namespaces = [{ binding = "SERVICES", id = "5f40026cc97041549aae3971b9334a8c", preview_id = "ac95881f85ef4751943d6a01ff92ce33" }]

[build]
command = "true"

[site]
bucket = ".output/public"
